### ISSUE TITLE
Block Type HorizontalDirectional && Directional Doesn't work

### ISSUE THREAD

**Issue by Qikahome** [gigaherz/JsonThings#52]
A block of type HorizontalDirectional or Directional does not contain attributes by default.
Even if I manually add the "facing" attribute, it doesn't work. (Doesn't automaticlly change its direction by player's direction)
That's because neither class Flex*Block nor their parents defines method getStateForPlacement.
May you fix it? or I will fix it by my self and open a new PR.

**Comment by gigaherz** [comment]
Sorry that it has taken me so long to get to this, I haven't had a lot of energy to work on my mods the last months, and then the 26.1 porting effort started, so I'm only getting to all the things I have been putting off.
I see that there is indeed some issue with those block types, I'm investigating why the logic goes wrong.

**Comment by Qikahome** [comment]
In fact, I have already fixed this issue in the 1.21.1 PR https://github.com/gigaherz/JsonThings/pull/54, you just need to check whether this code needs to be backported.

**Comment by gigaherz** [comment]
That PR does not fix this issue, though. It makes it possible for javascript scripts to override the `getStateForPlacement` logic, which I assumed was what you were asking for.

Before the PR, the code was already calling `super.getStateForPlacement`, this is how Java already works (methods are available through subclasses). I tested in 1.21.1 and a crash happens, which is what I thought you were asking for in this issue ticket:

https://github.com/user-attachments/assets/353825da-28ec-4f40-b0ed-0898bbf9e55e

I will be attempting to fix this crash today, and I will also backport and front-port the change from #54 to 1.20.1 and 26.1.

**Comment by Qikahome** [comment]
actually it does
in file [‎src/main/java/dev/gigaherz/jsonthings/things/blocks/FlexDirectionalBlock.java‎](https://github.com/gigaherz/JsonThings/pull/54/changes#diff-27e6e45a21c011c7128e818989bbfb1a0f1edbc6cd8021c3d047a724ab8e7c7b)
    public BlockState getStateForPlacement(BlockPlaceContext context) {
        return runEvent(FlexEventType.GET_STATE_FOR_PLACEMENT, FlexEventContext.of(context.getLevel(), context.getClickedPos(), this.defaultBlockState())
                .with(FlexEventContext.USER, context.getPlayer()).with(FlexEventContext.USE_CONTEXT, context).with(FlexEventContext.STATE_DEFINITION, this.stateDefinition)
                , **() -> this.defaultBlockState().setValue(FACING, context.getNearestLookingDirection().getOpposite()));**
    }

**Comment by Qikahome** [comment]
Okay, got it, need to manually define the direction in properties

**Comment by Qikahome** [comment]
If you don't do this, you will encounter another issue I mentioned on Discord:
"I suggest replacing
_properties.forEach(builder1::add);
with
for (Property<?> property : _properties) {
try {
builder1.add(property);
} catch (IllegalArgumentException e) {
//pass
}
}
because otherwise the shape property cannot obtain the block type's inherent shape, and it will crash if added manually."

**Comment by gigaherz** [comment]
I see, I did not notice that. HAving different code in different FlexBlock classes in the is not correct for the development style, since I expect all that section to be the same for all implementations so I can quickly copypaste it to all of them. I didn't notice this when the PR was made, so I overwrote those changes without realizing it. I apologize for that, but it means I have to find a different solution.

**Comment by Qikahome** [comment]
I used an enum in my json things extension to represent different placement rules, if this is of any reference value
https://github.com/Qikahome/JsonMore/blob/main/src/main/java/qikahome/jsonmore/lib/PlacingDirections.java

**Comment by gigaherz** [comment]
new versions for 26.1, 1.21.1, and 26.1 are on CF now, closing this.
